[[ 
| full |

full :=
 #('AST-Core'

 #'AST-FFI-Pharo50Compatibility'
 'AST-Tests-Core'
 #Alien
 'Announcements-Core'
 'Announcements-Help'
 'Announcements-Tests-Core'
 'Athens-Balloon'
 'Athens-Cairo'
 'Athens-CairoPools'
 'Athens-Core'
 'Athens-Examples'
 'Athens-Morphic'
 'Athens-Text'
 'Balloon'
 'Balloon-Tests'
 #BaselineOfFileTree
 #BaselineOfMetacello
 #BaselineOfQualityAssistant
 #BaselineOfRenraku
 'BlueInk-Core'
 'BlueInk-Extras'
 'BlueInk-Tests'
 #'Chroma-CubeHelix'
 'CodeExport'
 'CodeImport'
 'CodeImportCommandLineHandlers'
 'Collections-Abstract'
 'Collections-Arithmetic'
 'Collections-Atomic'
 'Collections-Native'
 'Collections-Sequenceable'
 'Collections-Stack'
 'Collections-Streams'
 'Collections-Strings'
 'Collections-Support'
 #'Collections-Tests'
 'Collections-Unordered'
 'Collections-Weak'
 'Compiler'
 'Compression'
 'Compression-Tests'
 'ConfigurationCommandLineHandler-Core'
 'ConfigurationCommandLineHandler-Tests'
 #ConfigurationOfAthens
 #ConfigurationOfCatalog
 #ConfigurationOfCodeImporter
 #ConfigurationOfDependencyAnalyser
 #ConfigurationOfFastTable
 #ConfigurationOfFuel
 #ConfigurationOfGTDebugger
 #ConfigurationOfGTEventRecorder
 #ConfigurationOfGTInspectorCore
 #ConfigurationOfGTPlaygroundCore
 #ConfigurationOfGTSpotter
 #ConfigurationOfGToolkitCore
 #ConfigurationOfGlamourCore
 #ConfigurationOfMooseAlgos
 #ConfigurationOfNautilusGroupAutoBuilder
 #ConfigurationOfOSWindow
 #ConfigurationOfPharoMetacello
 #ConfigurationOfQualityAssistant
 #ConfigurationOfRenraku
 #ConfigurationOfRubric
 #ConfigurationOfSessionManager
 #ConfigurationOfShoreLineReporter
 #ConfigurationOfSton
 #ConfigurationOfTxText
 #ConfigurationOfUnifiedFFI
 #ConfigurationOfVersionner
 #ConfigurationOfZincHTTPComponents
 'ContributingToTheCatalogHelp'
 #'Debugger-Tests'
 'DebuggerActions'
 'DebuggerFilters'
 'DebuggerModel'
 'Deprecated50'
 #EmbeddedFreeType
 'EmbeddedFreeType-Tests'
 'EmergencyEvaluator'
 #'FFI-Kernel'
 #'FFI-Pools'
 'FileSystem-Core'
 'FileSystem-Disk'
 'FileSystem-Memory'
 'FileSystem-Tests-Core'
 'FileSystem-Tests-Disk'
 'FileSystem-Tests-Memory'
 'FileSystem-Zip'
 'Files'
 'Files-Tests'
 #'Flashback-Decompiler'
 'Flashback-Decompiler-Tests'
 #FontChooser
 'FontInfrastructure'
 'FontInfrastructure-Tests'
 'FreeType'
 'FreeType-Tests'
 'Fuel'
 'FuelCommandLineHandler'
 #FuelPlatform
 'FuelSystem-FileRegistry'
 'FuelTests'
 'FuelTools-Debugger'
 #'GT-BytecodeDebugger'
 #'GT-Debugger'
 #'GT-EventRecorder'
 #'GT-EventRecorder-Tests'
 #'GT-Inspector'
 #'GT-InspectorExtensions-Core'
 #'GT-Playground'
 #'GT-SUnitDebugger'
 #'GT-Spotter'
 #'GT-Spotter-EventRecorder'
 #'GT-SpotterExtensions-Core'
 #'GT-Tests-Debugger'
 #'GT-Tests-Inspector'
 #'GT-Tests-Playground'
 #'GT-Tests-Spotter'
 #'Glamour-Announcements'
 'Glamour-Browsers'
 'Glamour-Core'
 'Glamour-Examples'
 #'Glamour-FastTable'
 'Glamour-Helpers'
 #'Glamour-Morphic-Brick'
 #'Glamour-Morphic-Brick-Tests'
 'Glamour-Morphic-Pager'
 'Glamour-Morphic-Renderer'
 'Glamour-Morphic-Theme'
 'Glamour-Morphic-Widgets'
 'Glamour-Presentations'
 'Glamour-Rubric-Presentations'
 'Glamour-Tests-Core'
 'Glamour-Tests-Morphic'
 'Glamour-Tests-Resources'
 'Glamour-Tests-Rubric'
 'Gofer-Core'
 'Gofer-Tests'
 'Gofer-UI'
 #'Graphics-Canvas'
 'Graphics-Display Objects'
 'Graphics-Files'
 'Graphics-Fonts'
 'Graphics-Primitives'
 #'Graphics-Shapes'
 'Graphics-Tests'
 'Graphics-Transformations'
 'Growl'
 'HelpSystem-Core'
 'HelpSystem-Tests'
 #HowToContributeHelp
 'HudsonBuildTools20'
 #'ImportingResource-Help'
 'IssueTracking'
 'IssueTracking-Tests'
 'Jobs'
 'JobsTests'
 'Kernel'
 'Kernel-Rules'
 'Kernel-Tests'
 'Keymapping-Core'
 'Keymapping-KeyCombinations'
 'Keymapping-Pragmas'
 'Keymapping-Settings'
 'Keymapping-Tests'
 'Keymapping-Tools-Spec'
 'Komitter'
 'Manifest-Core'
 'Manifest-Resources-Tests'
 'Manifest-Tests'
 'MenuRegistration'
 'MessageBrowserRefactoringAddition'
 'Metacello-Base'
 #'Metacello-Bitbucket'
 'Metacello-Core'
 'Metacello-FileTree'
 #'Metacello-GitBasedRepository'
 'Metacello-GitHub'
 'Metacello-MC'
 'Metacello-PharoCommonPlatform'
 #'Metacello-Platform'
 'Metacello-ProfStef'
 'Metacello-Reference'
 #'Metacello-TestsCommonMC'
 'Metacello-TestsCore'
 'Metacello-TestsMC'
 'Metacello-TestsMCCore'
 'Metacello-TestsMCResources'
 'Metacello-TestsPlatform'
 #'Metacello-TestsReference'
 'Metacello-ToolBox'
 'Metacello-Tutorial'
 'Monticello'
 'Monticello-OldDataStreamCompatibility'
 'Monticello-Tests'
 'MonticelloConfigurations'
 'MonticelloFileServices'
 'MonticelloFileTree-Core'
 'MonticelloFileTree-FileSystem-Utilities'
 'MonticelloGUI'
 'MonticelloMocks'
 'MonticelloRemoteRepositories'
 #'Moose-Algos-Graph'
 'Morphic-Base'
 'Morphic-Core'
 'Morphic-Examples'
 'Morphic-Tests'
 'Morphic-Widgets-Basic'
 #'Morphic-Widgets-ColorPicker'
 'Morphic-Widgets-Extra'
 #'Morphic-Widgets-FastTable'
 'Morphic-Widgets-List'
 'Morphic-Widgets-NewList'
 'Morphic-Widgets-Pluggable'
 'Morphic-Widgets-PolyTabs'
 'Morphic-Widgets-Scrolling'
 #'Morphic-Widgets-Tabs'
 'Morphic-Widgets-Taskbar'
 'Morphic-Widgets-TickList'
 'Morphic-Widgets-Tree'
 'Morphic-Widgets-Windows'
 'Multilingual-Encodings'
 'Multilingual-Languages'
 'Multilingual-OtherLanguages'
 'Multilingual-Tests'
 'Multilingual-TextConversion'
 'Multilingual-TextConverterOtherLanguages'
 'NECompletion'
 'NECompletion-Tests'
 'Nautilus'
 'Nautilus-GroupManager'
 'Nautilus-GroupManagerUI'
 'Nautilus-Tests'
 'NautilusCommon'
 #NautilusGroupAutoBuilder
 'NautilusRefactoring'
 'Network-Kernel'
 'Network-MIME'
 'Network-Mail'
 'Network-Protocols'
 'Network-Tests'
 'Network-UUID'
 'Network-Url'
 'NewValueHolder'
 'NodeNavigation'
 'NonInteractiveTranscript'
 #'OSWindow-Core'
 #'OSWindow-SDL2'
 #'OSWindow-SDL2-Examples'
 'OSWindow-Tests'
 #'OSWindow-VM'
 'OpalCompiler-Core'
 'OpalCompiler-Tests'
 'OpalTools'
 'Pharo-Help'
 'Polymorph-TaskbarIcons'
 'Polymorph-Widgets'
 'PragmaCollector'
 'ProfStef-Core'
 'ProfStef-Help'
 'ProfStef-Tests'
 #QualityAssistant
 #QualityAssistantRecording
 'RPackage-Core'
 'RPackage-Tests'
 'Random-Core'
 'Random-Tests'
 'RecentSubmissions'
 'Refactoring-Changes'
 'Refactoring-Core'
 'Refactoring-Critics'
 'Refactoring-Environment'
 'Refactoring-Tests-Changes'
 'Refactoring-Tests-Core'
 'Refactoring-Tests-Critics'
 'Refactoring-Tests-Environment'
 'Reflectivity'
 'Reflectivity-Examples'
 'Reflectivity-Tests'
 'Reflectivity-Tools'
 'Reflectivity-Tools-Tests'
 'Regex-Core'
 'Regex-Help'
 'Regex-Tests-Core'
 'ReleaseTests'
 #Renraku
 #'Renraku-Test'
 'Ring-Core-Containers'
 'Ring-Core-Kernel'
 'Ring-Monticello'
 'Ring-Tests-Containers'
 'Ring-Tests-Kernel'
 'Ring-Tests-Monticello'
 'RingChunkImporter'
 'Rubric'
 'Rubric-Rules'
 #'STON-Core'
 #'STON-Tests'
 'SUnit-Core'
 'SUnit-Help'
 'SUnit-Rules'
 'SUnit-Tests'
 'SUnit-UI'
 'SUnit-UITesting'
 #'ScriptLoader-Tests'
 #ScriptLoader60
 'Settings-Graphics'
 'Settings-Polymorph'
 'Settings-System'
 #'ShoreLine-Report-Core'
 #'ShoreLine-Report-Settings'
 #'ShoreLine-Report-UI'
 'Shout'
 'Shout-Tests'
 'Slot'
 'Slot-Tests'
 'SmartSuggestions'
 'SmartSuggestions-Tests'
 'Spec-Core'
 'Spec-Debugger'
 'Spec-Examples'
 'Spec-Help'
 'Spec-Inspector'
 'Spec-Layout'
 'Spec-MorphicAdapters'
 'Spec-PolyWidgets'
 'Spec-Tests'
 'Spec-Tools'
 'StartupPreferences'
 'System-Announcements'
 'System-BasicCommandLineHandler'
 'System-Caching'
 'System-CachingTests'
 'System-Changes'
 'System-Changes-FileServices'
 'System-Clipboard'
 'System-CommandLine'
 'System-CommandLine-TextSupport'
 'System-CommandLineHandler'
 'System-FileRegistry'
 'System-Finalization'
 'System-Hashing'
 'System-History'
 'System-History-Tests'
 'System-Installers'
 'System-Localization'
 'System-Localization-Tests'
 'System-Model'
 'System-OSEnvironments'
 'System-Object Events'
 'System-Platforms'
 'System-Serial Port'
 #'System-SessionManager'
 #'System-SessionManager-Tests'
 'System-Settings'
 'System-Settings-Tests'
 'System-Sound'
 'System-Sources'
 'System-Support'
 'System-SupportTests'
 'System-VMEvents'
 'Tests'
 'Text-Core'
 'Text-Diff'
 'Text-Edition'
 'Text-Edition-Tests'
 'Text-Scanning'
 'Text-Tests'
 'Tool-Base'
 #'Tool-Catalog'
 'Tool-CriticBrowser'
 'Tool-DependencyAnalyser'
 'Tool-DependencyAnalyser-Test'
 'Tool-DependencyAnalyser-UI'
 'Tool-Diff'
 'Tool-ExternalBrowser'
 'Tool-FileList'
 'Tool-FileList-Tests'
 'Tool-Finder'
 'Tool-ImageCleaner'
 'Tool-ProcessBrowser'
 'Tool-Profilers'
 'Tool-SystemReporter'
 'Tool-Transcript'
 #'Tool-TxWorkspace'
 'Tool-Workspace'
 'Tools'
 'Tools-Test'
 'Traits'
 'Transcript'
 #'TxText-Athens'
 #'TxText-AthensTests'
 #'TxText-Model'
 #'TxText-Styler'
 #'TxTextTests-Model'
 'UIManager'
 'Unicode-Initialization'
 #UnifiedFFI
 #'UnifiedFFI-Legacy'
 #'UnifiedFFI-Tests'
 'UpdateStreamer-Core'
 'UpdateStreamer-Tests'
 #'Versionner-Commit'
 'Versionner-Core-Announcements'
 'Versionner-Core-Commands'
 'Versionner-Core-DependenciesModel'
 'Versionner-Core-Model'
 'Versionner-Spec-Browser'
 'Versionner-Tests-Core-Commands'
 'Versionner-Tests-Core-DependenciesModel'
 'Versionner-Tests-Core-Model'
 'Versionner-Tests-Resources'
 'WorldMenuHelp'
 'WriteBarrierTests'
 'Zinc-Character-Encoding-Core'
 'Zinc-Character-Encoding-Tests'
 'Zinc-FileSystem'
 'Zinc-HTTP'
 'Zinc-Resource-Meta-Core'
 'Zinc-Resource-Meta-FileSystem'
 'Zinc-Resource-Meta-Tests'
 'Zinc-Tests'
 'Zinc-Zodiac'
 'Zodiac-Core'
 'Zodiac-Extra'
 'Zodiac-Tests').

full do: [ :pn | 
Transcript show: 'Loading '; show: pn; cr.

Gofer it smalltalkhubUser:  'Pharo' project:  'Pharo60'; package: pn;  load. ].

	
] on:  ProvideAnswerNotification do: [:e | 
  Transcript show: 'ProvideAnswerNotification '; show: e asString; cr.
  e resume:  ''].
] on:  MCMergeOrLoadWarning do: [:w | 
  Transcript show: 'MCMergeOrLoadWarning '; show: w asString; cr.
  w resume: true].	
  
  
 !
 
 Smalltalk tools register: GTGenericStackDebugger as: #debugger.

Smalltalk tools registeredDebuggersWithRanks.
Smalltalk tools debuggers add: (GTGenericStackDebugger->3).
Smalltalk tools debuggers add: (GTSUnitDebugger->70).
Smalltalk tools debuggers add: (GTBytecodeDebugger->5).

Smalltalk tools register: GTPlayground as: #workspace.
Smalltalk tools register: GTInspector as: #inspector.
Smalltalk tools register: ExternalChangesBrowser as: #changeList.
Smalltalk tools register: FileList as: #fileList.
Smalltalk tools register: Finder as: #finder.
Smalltalk tools register: ProcessBrowser as: #processBrowser.
Smalltalk tools register: RecentMessageList as: #recentMessageList.
Smalltalk tools register: SyntaxErrorDebugger as: #syntaxErrorDebugger.
Smalltalk tools register: TimeProfiler as: #timeProfiler.

(MorphicCoreUIManager classPool at: #UIProcess) terminate.
MorphicCoreUIManager classPool at: #UIProcess put: nil.

PolymorphSystemSettings desktopColor:  Color veryVeryLightGray lighter.
SourceCodeFonts setSourceCodeFonts: 10.
FreeTypeSystemSettings loadFt2Library: true.
FreeTypeSettings current monitorType: #LCD.
FreeTypeSettings current glyphContrast: 55.

RealEstateAgent usedStrategy: #cascadeFor:initialExtent:world:.
GrowlMorph position: #bottomLeft.
ShortcutReminder enabled: true.

OSTouchOneFingerDoubleTapDetector maxDistance: 0.05.
OSTouchOneFingerDoubleTapDetector doubleTouchSpeed: 700.
OSTouchPinchDetector maxDistanceBetweenFingersLine: 0.2.
OSTouchPinchDetector minDistanceBeforeDetection: 0.05.
OSTouchRotationDetector minAngleBeforeDetection: 10.
OSTouchScrollDetector minDistanceBeforeDetection: 0.05.
OSTouchScrollDetector persistentDirection: false.
OSTouchSwipeDetector minDistToBorder: 0.1.
OSTouchSwipeDetector minDistanceBeforeDetection: 0.05.

QASettings nautilusPlugin: true.

KMRepository reset.
Morph shortcutsHandler: KMShortcutHandler new.

"because of Komitter"
MCSaveVersionDialog previousMessages add: String new.

RBProgramNode formatterClass: BIConfigurableFormatter.